name: cyber-battle # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Cyber Battle Saga
summary: Fight through futuristic battle zones.
description: Use technology-powered warriors to dominate foes and win battles in neon-lit cyber cities.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  cyber-battle:
    command: bin/cyber-battle-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  cyber-battle:
    plugin: dump
    source: .
    organize:
      cyber-battle-bin: bin/
